config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  root to: "home#index"

  resources :products

  resources :session

  #resources for admin
  resources :admin, only: [:new, :create, :destroy]

  resources :page

  resources :user do
  	resources :message , only: [ :new , :index , :destroy , :create , :edit , :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy


  def add_product(product, currentuser)
    item = line_items.find_by(product: product, current_user_id: currentuser)

    if item
      item.quantity += 1
    else
      item = line_items.new(product: product, current_user_id: currentuser)
    end
    item
  end

  def total
    line_items.to_a.sum(&:total)
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total
    product.price * quantity
  end

end

app/models/message.rb
class Message < ApplicationRecord
	validates :contenu, presence: true
	belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items, dependent: :nullify
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :messages
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def new; end

  def create
     admin_input_email = params[:email]
     admin_input_password = params[:password]

    puts admin = Admin.find_by(email: admin_input_email)

    if admin && admin.authenticate(admin_input_password)
      # puts "tafiditra"
      session[:admin_id] = admin.id
      redirect_to products_path

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:admin_id)
    redirect_to root_path
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #only for specified current_user
    def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_product, only: [:show]

  # GET /products
  # GET /products.json
  def index
    # @products = Product.order(:title)
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image_url)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  
  def index
    @id = session[:id]
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
 
  def new
  end

  def create

  	puts '*' * 100

  	User.create(nom: params[:Nom] , prenom: params[:Prenom] , age: params[:Age] , email: params[:Email] , password: params[:password])
  	
  	redirect_to new_session_path

  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def current_admin
    Admin.find_by(id: session[:admin_id])
 end

  def log_in(admin)
    session[:admin_id] = admin.id
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/page_helper.rb
module PageHelper

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def current_user
    User.find_by(id: session[:id])
  end

  def log_in(user)
   session[:user_id] = user.id
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <link rel="stylesheet" type="text/css" href="/css/admin.css">
</head>




<body>





<div id="admin" class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div id="admin" class="card card-signin my-5">
          <div class="card-body">
            <h3 class="card-title text-center">Login<span id="spa" >ADMIN</span> </h3>
           
            <form class="form-signin" accept-charset="UTF-8" action="<%= admin_index_path %>" method="post" >

              
              <%= token_tag %>
              <input name="utf8" type="hidden" value="&#x2713;"/>



              
              <div class="form-label-group">
                <label for="inputEmail">Email address</label>
                <input name='email' type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
                
              </div>

              <div class="form-label-group">
                <label  for="inputPassword">Password</label>
                <input name='password' type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
                
              </div>

  
             <button id="btn" class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign in</button>
              <hr class="my-4">
             
             <!--  <button class="btn btn-lg btn-google btn-block text-uppercase" type="submit"><i class="fab fa-google mr-2"></i> Sign in with Google</button>
             
              <button class="btn btn-lg btn-facebook btn-block text-uppercase" type="submit"><i class="fab fa-facebook-f mr-2"></i> Sign in with Facebook</button> -->

            </form>

          </div>
        </div>
      </div>
    </div>
  </div>












  </body>
</html>


</body>


</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Vita</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />

    <link rel="stylesheet" type="text/css" href="/bootstrap/bootstrap.min.css">


    <script src="jquery/jquery.js"></script>
    <script src="bootstrap/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/css/acceuil.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style href=/app/assets/stylesheet/index.css></style>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>



  <body>
    
    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>

	<link rel="stylesheet" type="text/css" href="/acceuil.css">
	<link rel="stylesheet" type="text/css" href="/bootstrap.min.css">


	<script src="/jquery.js"></script>
    <script src="/bootstrap.min.js"></script></head>


<body class="body" >

	<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  
      <p class="logo"> Sayna<span class="spa">Hub</span> </p>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        
        <ul class="navbar-nav">
          
                <li class="nav-item">
                  <a class="nav-link" href="/page">Acceuil</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="/user/<%= current_user.id %>/message">Forum</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="#">Team</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="#">Contact</a>
                </li> 

                <li class="nav-item">
                  <% if(current_user) %>
                    <!-- <a class="nav-link" href="/session/<""%= @id %>" data-method="delete" >Log Out</a> -->
                    <%= link_to "Log Out", session_path(current_user.id), method: :delete, class: 'nav-link' %>

                  <%else%>
                     <a class="nav-link" href=<%= new_session_path %>>Log In</a>
                  <%end%>
               </li>
                    
               
         </ul>

      </div> 

</nav>


<h1>ACCEUIL</h1>
















  <tbody>

          <% @products.each do |product| %>

              <tr>
                <td><%= image_tag product.image_url, width: 250 %></td>
                <!-- -->
                <td><%= product.title %></td>
                <!--truncate=> avec la parametre length permet de couper un text; strip_tags=>supprime ts les balises html de la chaine -->
                <td><%= truncate strip_tags(product.description), length: 250 %></td>
                <!--number_to_currency: pr avoir unité, format: "%n/u" : n=>nombre puis unité-->
                <td><%= number_to_currency product.price, unit: "MGA ", separator: ",", format: "%u%n" %></td>
                <!-- image_tag => recu de l'image dans app/assets/images -->
                <!-- <td> <''%= link_to 'Show', catalog_url(product), class: "btn btn-primary" %></td> -->
                <!-- lien d'ajout au panier -->
                <!-- <td><''%= button_to 'Ajouter au panier', line_items_path(product_id: product), class: "btn btn-primary" %></td> -->
                <% if(current_user) %>
                    <td><%= button_to 'Ajouter au panier', line_items_path(product_id: product), class: "btn btn-primary" %></td>
                  <%else%>
                    <td><%= link_to 'Ajouter au panier', new_session_path, class: "btn btn-primary" %></td>
                <%end%>
              </tr>
            <% end %>
      
      </tbody>







<%if current_user%>
  <%= current_user.id%>
  <%else%>
  <p>no user</p>
<%end%>



</body>
</html>